// AUTOGENERATED FILE FROM game_boy_graphics_editor
#ifndef MAP_Background_H
#define MAP_Background_H
#define Background_TILE_ORIGIN 0
#define Background_WIDTH 32
#define Background_HEIGHT 18

extern const unsigned char BackgroundMap[];

#endif
